import type { CSSProperties } from "react";

/** Co-located styles for the Project Context picker. */
export const s = {
  wrap: { maxWidth: 860, padding: "24px 28px" } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 8 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  count: {
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--accent-text)",
    background: "var(--accent-bg)",
    padding: "2px 10px",
    borderRadius: 5,
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  filter: { marginLeft: "auto", width: 240 } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-muted)", marginBottom: 18, lineHeight: 1.5 } satisfies CSSProperties,
  inlineCode: { color: "var(--text-secondary)", fontSize: 12.5 } satisfies CSSProperties,
  note: { fontSize: 13, color: "var(--text-muted)", padding: "16px 0" } satisfies CSSProperties,
  warn: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12.5,
    color: "var(--warn)",
    background: "var(--warn-bg)",
    border: "1px solid color-mix(in srgb, var(--warn) 30%, transparent)",
    borderRadius: 7,
    padding: "8px 12px",
    marginBottom: 12,
  } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: (checked: boolean, dragging: boolean, drop: "before" | "after" | null): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "11px 14px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: checked ? "var(--bg-hover)" : "var(--bg-elevated)",
    opacity: dragging ? 0.5 : 1,
    boxShadow:
      drop === "before" ? "0 -2px 0 0 var(--accent)" : drop === "after" ? "0 2px 0 0 var(--accent)" : "none",
  }),
  grip: (enabled: boolean): CSSProperties => ({
    display: "inline-flex",
    color: "var(--text-muted)",
    cursor: enabled ? "grab" : "default",
    opacity: enabled ? 1 : 0.45,
    flexShrink: 0,
  }),
  name: {
    fontSize: 13.5,
    fontWeight: 600,
    color: "var(--text-primary)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: 320,
  } satisfies CSSProperties,
  dir: {
    fontSize: 12,
    color: "var(--text-muted)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: 220,
  } satisfies CSSProperties,
  tag: {
    fontSize: 11.5,
    color: "var(--text-secondary)",
    border: "1px solid var(--border)",
    borderRadius: 4,
    padding: "1px 7px",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  missing: {
    fontSize: 11.5,
    color: "var(--warn)",
    background: "var(--warn-bg)",
    borderRadius: 4,
    padding: "1px 7px",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  moveBtns: { display: "inline-flex", gap: 2 } satisfies CSSProperties,
  moveBtn: (disabled: boolean): CSSProperties => ({
    background: "none",
    border: "none",
    padding: 3,
    display: "inline-flex",
    color: disabled ? "var(--text-muted)" : "var(--text-secondary)",
    opacity: disabled ? 0.35 : 1,
    cursor: disabled ? "not-allowed" : "pointer",
  }),
  previewBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    color: "var(--text-secondary)",
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "4px 10px",
    cursor: "pointer",
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginTop: 20,
    paddingTop: 14,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  footerLeft: { marginTop: 12 } satisfies CSSProperties,
  tokens: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  footerNote: { marginLeft: "auto", fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  serialLabel: {
    marginTop: 22,
    marginBottom: 8,
    fontSize: 11.5,
    fontWeight: 600,
    letterSpacing: "0.08em",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  serialBox: {
    margin: 0,
    padding: "14px 16px",
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    fontSize: 12.5,
    lineHeight: 1.7,
    color: "var(--text-secondary)",
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,
} as const;
