import type { CSSProperties } from "react";

/** Co-located styles for the agent editor's Skills tab. */
export const s = {
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 6 } satisfies CSSProperties,
  title: { fontSize: 17, fontWeight: 700 } satisfies CSSProperties,
  hint: {
    fontSize: 13,
    color: "var(--text-muted)",
    margin: "10px 0 16px",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  search: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 11px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    width: 220,
    marginLeft: "auto",
  } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: (active: boolean, dragOver: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px solid " + (dragOver ? "var(--accent)" : "var(--border)"),
    background: active ? "var(--bg-hover)" : "var(--bg-elevated)",
  }),
  handle: {
    color: "var(--text-muted)",
    cursor: "grab",
    display: "inline-flex",
    flexShrink: 0,
  } satisfies CSSProperties,
  name: (struck: boolean): CSSProperties => ({
    fontSize: 14,
    fontWeight: 600,
    flex: 1,
    minWidth: 0,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    textDecoration: struck ? "line-through" : "none",
    color: struck ? "var(--text-muted)" : "var(--text-primary)",
  }),
  typeChip: (color: string): CSSProperties => ({
    fontSize: 11,
    fontWeight: 600,
    color,
    background: color + "1a",
    padding: "2px 8px",
    borderRadius: 4,
    flexShrink: 0,
  }),
  orderBtns: { display: "flex", gap: 2, flexShrink: 0 } satisfies CSSProperties,
  iconButton: (disabled: boolean): CSSProperties => ({
    background: "none",
    border: "none",
    padding: 3,
    display: "inline-flex",
    color: disabled ? "var(--border-strong)" : "var(--text-muted)",
    cursor: disabled ? "default" : "pointer",
  }),
  globalOff: { fontSize: 11, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginTop: 18,
  } satisfies CSSProperties,
  savedNote: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
