import type { CSSProperties } from "react";

/** Co-located styles for the Project Context page. */
export const s = {
  frame: { display: "flex", height: "calc(100vh - 52px)" } satisfies CSSProperties,
  side: {
    width: 330,
    flexShrink: 0,
    borderRight: "1px solid var(--border)",
    background: "var(--bg-surface)",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
  } satisfies CSSProperties,
  sideHead: { padding: "20px 18px 10px" } satisfies CSSProperties,
  label: { fontSize: 12, fontWeight: 600, letterSpacing: "0.1em", color: "var(--text-muted)" } satisfies CSSProperties,
  roots: { fontSize: 13, color: "var(--text-secondary)", marginTop: 6 } satisfies CSSProperties,
  toolbar: { display: "flex", alignItems: "center", gap: 6, margin: "14px 0 12px" } satisfies CSSProperties,
  list: { flex: 1, overflow: "auto", padding: "0 10px 12px" } satisfies CSSProperties,
  item: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    textAlign: "left",
    padding: "9px 10px",
    borderRadius: 7,
    border: "none",
    background: active ? "var(--bg-hover)" : "transparent",
    color: active ? "var(--text-primary)" : "var(--text-secondary)",
    cursor: "pointer",
  }),
  itemText: { display: "flex", flexDirection: "column", minWidth: 0 } satisfies CSSProperties,
  itemName: {
    fontSize: 13.5,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  itemDir: {
    fontSize: 11.5,
    color: "var(--text-muted)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  sideFoot: {
    borderTop: "1px solid var(--border)",
    padding: "12px 18px",
    fontSize: 12.5,
    color: "var(--text-muted)",
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  dot: { width: 7, height: 7, borderRadius: 99, background: "var(--ok)", marginTop: 6, flexShrink: 0 } satisfies CSSProperties,
  main: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", minHeight: 0 } satisfies CSSProperties,
  mainHead: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "18px 28px",
    borderBottom: "1px solid var(--border)",
    flexShrink: 0,
  } satisfies CSSProperties,
  path: { fontSize: 15, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  mode: {
    fontSize: 12.5,
    fontWeight: 600,
    padding: "4px 12px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-hover)",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  meta: { marginLeft: "auto", display: "flex", alignItems: "center", gap: 16, fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  metaItem: { display: "inline-flex", alignItems: "center", gap: 6 } satisfies CSSProperties,
  body: { flex: 1, overflow: "auto", padding: "28px 40px 40px" } satisfies CSSProperties,
  doc: { maxWidth: 820, fontSize: 15 } satisfies CSSProperties,
  readOnly: { fontSize: 12, color: "var(--text-muted)", marginBottom: 18 } satisfies CSSProperties,
  center: { flex: 1, display: "grid", placeItems: "center", color: "var(--text-muted)", fontSize: 14 } satisfies CSSProperties,
  note: { fontSize: 12.5, color: "var(--text-muted)", padding: "8px 10px" } satisfies CSSProperties,
} as const;
