import type { CSSProperties } from "react";
import { RAIL_WIDTH } from "./constants";

/** Shared styles for the Skills rail + skill editor layout. */
export const s = {
  // ---- page shell ----
  layout: { display: "flex", height: "calc(100vh - 52px)" } satisfies CSSProperties,
  rail: {
    width: RAIL_WIDTH,
    flexShrink: 0,
    borderRight: "1px solid var(--border)",
    display: "flex",
    flexDirection: "column",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  railHeader: { padding: "16px 16px 12px" } satisfies CSSProperties,
  railTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 14,
  } satisfies CSSProperties,
  railTitle: { fontSize: 18, fontWeight: 700, flex: 1 } satisfies CSSProperties,
  search: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  railList: { flex: 1, overflow: "auto", padding: "0 12px 12px" } satisfies CSSProperties,
  detail: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    minHeight: 0,
  } satisfies CSSProperties,
  selectPrompt: {
    flex: 1,
    display: "grid",
    placeItems: "center",
    textAlign: "center",
    padding: 40,
  } satisfies CSSProperties,

  // ---- rail card ----
  card: (active: boolean, enabled: boolean): CSSProperties => ({
    padding: 12,
    borderRadius: 8,
    cursor: "pointer",
    border: "1px solid " + (active ? "var(--border-strong)" : "var(--border)"),
    background: active ? "var(--bg-hover)" : "var(--bg-elevated)",
    opacity: enabled ? 1 : 0.55,
    marginBottom: 10,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  }),
  cardHeader: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  iconBox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    background: "var(--accent-bg)",
    color: "var(--accent)",
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
  } satisfies CSSProperties,
  cardName: {
    fontSize: 13,
    fontWeight: 600,
    flex: 1,
    minWidth: 0,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  cardDescription: {
    fontSize: 12,
    color: "var(--text-muted)",
    lineHeight: 1.4,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  cardMeta: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  cardFooter: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    paddingTop: 8,
    borderTop: "1px solid var(--border)",
    fontSize: 11,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  typeChip: (color: string): CSSProperties => ({
    fontSize: 11,
    fontWeight: 600,
    color,
    background: color + "1a",
    padding: "2px 8px",
    borderRadius: 4,
    flexShrink: 0,
  }),
  sourceChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11,
    color: "var(--text-muted)",
  } satisfies CSSProperties,

  // ---- detail header + tabs ----
  detailHeader: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "16px 28px 0",
    flexShrink: 0,
  } satisfies CSSProperties,
  detailName: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  tabsBar: { marginTop: 14 } satisfies CSSProperties,
  tabBody: { flex: 1, minHeight: 0, overflow: "auto", padding: 28 } satisfies CSSProperties,

  // ---- config tab ----
  sectionRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 22,
  } satisfies CSSProperties,
  sectionTitle: { fontSize: 17, fontWeight: 700 } satisfies CSSProperties,
  enabledLabel: {
    marginLeft: "auto",
    fontSize: 13,
    color: "var(--text-secondary)",
    fontWeight: 600,
  } satisfies CSSProperties,
  editorFrame: {
    borderRadius: 8,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    overflow: "hidden",
  } satisfies CSSProperties,
  editorBar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 12px",
    borderBottom: "1px solid var(--border)",
    background: "var(--bg-surface)",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  editorFilename: { color: "var(--text-secondary)", fontWeight: 600 } satisfies CSSProperties,
  editorTokens: { marginLeft: "auto" } satisfies CSSProperties,
  editorPane: { display: "flex", alignItems: "stretch" } satisfies CSSProperties,
  gutter: {
    padding: "10px 8px 10px 12px",
    textAlign: "right",
    color: "var(--text-muted)",
    fontSize: 12.5,
    lineHeight: "20px",
    userSelect: "none",
    borderRight: "1px solid var(--border)",
    background: "var(--bg-surface)",
    minWidth: 44,
  } satisfies CSSProperties,
  bodyInput: {
    flex: 1,
    minHeight: 380,
    resize: "vertical",
    padding: "10px 12px",
    border: "none",
    outline: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 12.5,
    lineHeight: "20px",
    whiteSpace: "pre",
    overflowWrap: "normal",
    overflowX: "auto",
  } satisfies CSSProperties,
  fieldHint: {
    fontSize: 12,
    color: "var(--text-muted)",
    marginTop: 8,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  actions: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginTop: 22,
  } satisfies CSSProperties,

  // ---- preview tab ----
  previewIntro: { marginBottom: 18 } satisfies CSSProperties,
  previewSubtitle: {
    fontSize: 13,
    color: "var(--text-muted)",
    marginTop: 4,
  } satisfies CSSProperties,
  previewCard: {
    padding: 24,
    borderRadius: 10,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    fontSize: 14,
  } satisfies CSSProperties,

  // ---- stats tab ----
  tiles: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))",
    gap: 14,
    marginBottom: 18,
  } satisfies CSSProperties,
  tile: {
    padding: "16px 18px",
    borderRadius: 10,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  tileLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
    textTransform: "uppercase",
  } satisfies CSSProperties,
  tileValue: {
    fontSize: 30,
    fontWeight: 700,
    marginTop: 10,
    display: "flex",
    alignItems: "baseline",
    gap: 6,
  } satisfies CSSProperties,
  tileUnit: { fontSize: 14, fontWeight: 500, color: "var(--text-muted)" } satisfies CSSProperties,
  tileNote: { fontSize: 11, color: "var(--text-muted)", marginTop: 8, lineHeight: 1.4 } satisfies CSSProperties,
  panel: {
    padding: 18,
    borderRadius: 10,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  panelTitle: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
    textTransform: "uppercase",
    marginBottom: 14,
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  agentRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    marginBottom: 8,
  } satisfies CSSProperties,
  agentName: { fontSize: 13, fontWeight: 600, flex: 1 } satisfies CSSProperties,

  // ---- versions tab ----
  versionRow: (current: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "14px 16px",
    borderRadius: 9,
    border: "1px solid " + (current ? "var(--border-strong)" : "var(--border)"),
    background: current ? "var(--bg-hover)" : "var(--bg-elevated)",
    marginBottom: 10,
  }),
  versionBadge: {
    fontSize: 12,
    fontWeight: 700,
    color: "var(--accent)",
    background: "var(--accent-bg)",
    padding: "4px 9px",
    borderRadius: 6,
    flexShrink: 0,
  } satisfies CSSProperties,
  versionText: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  versionSummary: { fontSize: 13.5, fontWeight: 600 } satisfies CSSProperties,
  versionDate: { fontSize: 12, color: "var(--text-muted)", marginTop: 4 } satisfies CSSProperties,
  diffBlock: {
    marginTop: 10,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    maxHeight: 300,
    overflow: "auto",
    fontSize: 12.5,
    lineHeight: "19px",
  } satisfies CSSProperties,
  diffLine: (kind: "add" | "remove" | "same"): CSSProperties => ({
    padding: "0 12px",
    whiteSpace: "pre-wrap",
    color:
      kind === "add" ? "var(--ok, #3fb950)" : kind === "remove" ? "var(--danger)" : "var(--text-muted)",
    background:
      kind === "add"
        ? "rgba(63,185,80,0.08)"
        : kind === "remove"
          ? "rgba(248,81,73,0.08)"
          : "transparent",
  }),
  emptyNote: {
    fontSize: 13,
    color: "var(--text-muted)",
    lineHeight: 1.6,
  } satisfies CSSProperties,

  // ---- import drawer ----
  drawerBody: { display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  drawerFooter: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  notice: {
    display: "flex",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--warning-border, var(--border-strong))",
    background: "var(--bg-hover)",
    fontSize: 13,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  fileRow: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  fileName: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  ignoredList: {
    margin: 0,
    padding: "8px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    maxHeight: 160,
    overflow: "auto",
    listStyle: "none",
    fontSize: 12,
    color: "var(--text-muted)",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-secondary)",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  } satisfies CSSProperties,
  previewBody: {
    padding: 16,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    fontSize: 13,
    maxHeight: "52vh",
    overflow: "auto",
  } satisfies CSSProperties,
  error: { fontSize: 13, color: "var(--danger)" } satisfies CSSProperties,
} as const;
