import type { CSSProperties } from "react";

/** Co-located styles for VersionsTab. */
export const s = {
  wrap: { maxWidth: 900, padding: "20px 28px" } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 6 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  badge: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-secondary)",
    background: "var(--bg-hover)",
    padding: "2px 10px",
    borderRadius: 5,
  } satisfies CSSProperties,
  explanation: { fontSize: 13, color: "var(--text-muted)", marginTop: 8, marginBottom: 18, lineHeight: 1.5 } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "12px 16px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  versionBadge: {
    fontSize: 12,
    fontWeight: 700,
    fontFamily: "var(--font-mono, monospace)",
    color: "var(--text-secondary)",
    background: "var(--bg-hover)",
    borderRadius: 5,
    padding: "2px 8px",
    flexShrink: 0,
  } satisfies CSSProperties,
  rowMain: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  date: { fontSize: 12, color: "var(--text-muted)", marginTop: 2 } satisfies CSSProperties,
  currentBadge: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--ok)",
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
  } satisfies CSSProperties,
  rowActions: { display: "flex", gap: 8, flexShrink: 0 } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)", padding: "24px 0" } satisfies CSSProperties,
  diffPanel: {
    marginTop: 8,
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
  } satisfies CSSProperties,
  diffPane: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: "12px 14px",
    background: "var(--bg-surface)",
    maxHeight: 320,
    overflow: "auto",
  } satisfies CSSProperties,
  diffLabel: { fontSize: 11, fontWeight: 600, color: "var(--text-muted)", marginBottom: 6 } satisfies CSSProperties,
  diffBody: {
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
    whiteSpace: "pre-wrap",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
} as const;
